export const WORD_LOADING_STATUS = "WORD_LOADING_DATA";
export const WORD_SUCCESS_DATA = "WORD_SUCCESS_DATA";
export const WORD_FAILURE_DATA = "WORD_FAILURE_DATA";

export const ADD_TO_HISTORY = "ADD_TO_HISTORY"
